### ISSUE TITLE
Not able to download

### ISSUE THREAD

**Issue by Brodieman** [Azmekk/yt-dlp-web-app#2]
Trying out this app, was able to get it running.  When I try and download a video it says it failed.  I am running this on TrueNAS Scale as a custom app with user 568 (which is their apps user, I need this for the downloads folder mapping).

Seeing lots in the logs but this one sticks out

`PermissionError: [Errno 13] Permission denied: '/.cache'`

Any thoughts?  That would be inside the container, no?

**Comment by Brodieman** [comment]
Whelp, I am an id10t, I had the path wrong to the dataset but I am still seeing the /.cache permissions error.

**Comment by Azmekk** [comment]
Hmm this definitely seems like a permission error, however I am not sure what is causing it. This is a bit of a blind guess, but it might actually be `yt-dlp` since it's the only python component in the whole app and afaik some python libs like to utilize `/.cache.` _Don't quote me on this though, since I might be wrong_ :D That theory would also be backed by the fact that you get the error when you try to download a video which is when `yt-dlp` is invoked.

To be fair I've never used this in an environment like Unraid or TrueNAS so I am unaware of the caveats regarding these. Can you try spinning up a container that consists only of yt-dlp (maybe something like [this](https://hub.docker.com/r/tnk4on/yt-dlp)) and see if it works for you?

PS.
I'm honestly quite unhappy with how this app came out and I'm writing a replacement for it that ditches the whole sqlite db (originally intended to have a desktop version but gave up) so I will be making a new one relatively soon anyways.

**Comment by Brodieman** [comment]
@Azmekk No worries, generally TreuNAS app works 99% like Docker it's just in how it stores the container in the OS that adds that little kick of unknown.  But at it's core it's just docker. The app seems decent enough UI wise and it's easy to start a download.  Not sure when I'll have time to try the only yt-dlp  test.

Would the fact that I am running as 568 be the issue you thing?  I am horrible when it comes to unix permissions.  It would be like, in a compose file, doing user: "568:568"

**Comment by Azmekk** [comment]
Also one more thing that occurred to me.

1. Can you try mapping an external volume to /.cache? 

Docker Compose:
```
volumes:
  - "/hostpath/cache:/.cache"
```

Docker Run:
```
-v /hostpath/cache:/.cache 
```
then ensure user 568 has perms with `chown -R 568:568 /hostpath/cache`

`Edit:` Didn't see your reply while writing this, but yes I suspect user perms are the root cause of this, hence the 2 suggestions earlier. Let me know if you want the full updated compose file or `docker run` command

**Comment by Brodieman** [comment]
Mapping the cache was a genius idea but still failing.  I ran the chown and it did not return an error, so host permissions seem to be correct.  Maybe, internally, the app just does not like being run as 568?

**Comment by Azmekk** [comment]
Hmm what makes this more interesting is that I tried to `ls` that path in my container and it doesn't even exist. Nor have I ever gotten that error when looking at logs, despite the path not existing. That is actually so bizarre.

<img width="963" height="37" alt="Image" src="https://github.com/user-attachments/assets/12b35526-b513-45bf-a388-38beea4b7fab" />

Just to confirm, you got the image from the [dockerhub repo](https://hub.docker.com/repository/docker/azmek/yt-dlp-web-app/general) right? aka `image: azmek/yt-dlp-web-app:latest`  Don't think it matters but just curious in case you decided to build the project yourself.

Also I pushed an update to the project because sometimes video downloads fail because the yt-dlp binary is a few versions behind the latest and I have to rebuild the whole container in order to update to the latest ver (aiming to fix that in my future app as well). Can you try deleting the container and image and pulling everything from scratch?

**Comment by Brodieman** [comment]
I am using `azmek/yt-dlp-web-app:latest`.  I did look and notice that directory didn't exist but I thought maybe it was some super hidden\protected directory or something.  I am not sure how to tell what version I am on to verify but I think I tried to update the container.  Still failing.  It honestly might not be your app\problem?  Remember I am using this on TrueNAS Scale.
